// Mocks generated by Mockito 5.4.6 from annotations
// in aimo_wallet/test/features/wallet/presentation/controllers/wallet_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aimo_wallet/features/wallet/domain/usecases/create_new_wallet_usecase.dart'
    as _i2;
import 'package:aimo_wallet/features/wallet/domain/usecases/get_current_address_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCreateNewWalletResult_0 extends _i1.SmartFake
    implements _i2.CreateNewWalletResult {
  _FakeCreateNewWalletResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CreateNewWalletUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNewWalletUseCase extends _i1.Mock
    implements _i2.CreateNewWalletUseCase {
  MockCreateNewWalletUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.CreateNewWalletResult> call({required String? pin}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#pin: pin}),
            returnValue: _i3.Future<_i2.CreateNewWalletResult>.value(
              _FakeCreateNewWalletResult_0(
                this,
                Invocation.method(#call, [], {#pin: pin}),
              ),
            ),
          )
          as _i3.Future<_i2.CreateNewWalletResult>);
}

/// A class which mocks [GetCurrentAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentAddressUseCase extends _i1.Mock
    implements _i4.GetCurrentAddressUseCase {
  MockGetCurrentAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(this, Invocation.method(#call, [])),
            ),
          )
          as _i3.Future<String>);
}
