// Mocks generated by Mockito 5.4.6 from annotations
// in aimo_wallet/test/features/wallet/domain/usecases/create_new_wallet_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i3;

import 'package:aimo_wallet/core/crypto/wallet_engine.dart' as _i2;
import 'package:aimo_wallet/core/vault/secure_vault.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWalletCreationResult_0 extends _i1.SmartFake
    implements _i2.WalletCreationResult {
  _FakeWalletCreationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalletImportResult_1 extends _i1.SmartFake
    implements _i2.WalletImportResult {
  _FakeWalletImportResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountDerivationResult_2 extends _i1.SmartFake
    implements _i2.AccountDerivationResult {
  _FakeAccountDerivationResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalletEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletEngine extends _i1.Mock implements _i2.WalletEngine {
  MockWalletEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WalletCreationResult createWallet() =>
      (super.noSuchMethod(
            Invocation.method(#createWallet, []),
            returnValue: _FakeWalletCreationResult_0(
              this,
              Invocation.method(#createWallet, []),
            ),
          )
          as _i2.WalletCreationResult);

  @override
  _i2.WalletImportResult importWallet(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#importWallet, [mnemonic]),
            returnValue: _FakeWalletImportResult_1(
              this,
              Invocation.method(#importWallet, [mnemonic]),
            ),
          )
          as _i2.WalletImportResult);

  @override
  _i2.AccountDerivationResult deriveAccount(String? mnemonic, int? index) =>
      (super.noSuchMethod(
            Invocation.method(#deriveAccount, [mnemonic, index]),
            returnValue: _FakeAccountDerivationResult_2(
              this,
              Invocation.method(#deriveAccount, [mnemonic, index]),
            ),
          )
          as _i2.AccountDerivationResult);

  @override
  _i3.Uint8List derivePrivateKeyForAccount(
    String? mnemonic, {
    int? index = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePrivateKeyForAccount,
              [mnemonic],
              {#index: index},
            ),
            returnValue: _i3.Uint8List(0),
          )
          as _i3.Uint8List);

  @override
  bool validateMnemonic(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#validateMnemonic, [mnemonic]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [SecureVault].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureVault extends _i1.Mock implements _i4.SecureVault {
  MockSecureVault() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> storeMnemonic(
    String? mnemonic,
    String? pin, {
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeMnemonic,
              [mnemonic, pin],
              {#address: address},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> retrieveMnemonic(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#retrieveMnemonic, [pin]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#retrieveMnemonic, [pin]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> hasWallet() =>
      (super.noSuchMethod(
            Invocation.method(#hasWallet, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> deleteWallet() =>
      (super.noSuchMethod(
            Invocation.method(#deleteWallet, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getWalletAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getWalletAddress, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> verifyPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [pin]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> updatePin(String? oldPin, String? newPin) =>
      (super.noSuchMethod(
            Invocation.method(#updatePin, [oldPin, newPin]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
