// Mocks generated by Mockito 5.4.6 from annotations
// in aimo_wallet/test/features/wallet/domain/usecases/get_current_address_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aimo_wallet/core/vault/secure_vault.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SecureVault].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureVault extends _i1.Mock implements _i2.SecureVault {
  MockSecureVault() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> storeMnemonic(
    String? mnemonic,
    String? pin, {
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeMnemonic,
              [mnemonic, pin],
              {#address: address},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> retrieveMnemonic(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#retrieveMnemonic, [pin]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#retrieveMnemonic, [pin]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> hasWallet() =>
      (super.noSuchMethod(
            Invocation.method(#hasWallet, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteWallet() =>
      (super.noSuchMethod(
            Invocation.method(#deleteWallet, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getWalletAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getWalletAddress, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> verifyPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [pin]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updatePin(String? oldPin, String? newPin) =>
      (super.noSuchMethod(
            Invocation.method(#updatePin, [oldPin, newPin]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
