// Mocks generated by Mockito 5.4.6 from annotations
// in aimo_wallet/test/features/wallet/data/repositories/wallet_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:aimo_wallet/core/crypto/bip39_service.dart' as _i7;
import 'package:aimo_wallet/core/crypto/key_derivation_service.dart' as _i3;
import 'package:aimo_wallet/core/vault/encryption_service.dart' as _i2;
import 'package:aimo_wallet/features/wallet/data/datasources/secure_storage_datasource.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEncryptedData_0 extends _i1.SmartFake implements _i2.EncryptedData {
  _FakeEncryptedData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalletKeys_1 extends _i1.SmartFake implements _i3.WalletKeys {
  _FakeWalletKeys_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SecureStorageDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageDataSource extends _i1.Mock
    implements _i4.SecureStorageDataSource {
  MockSecureStorageDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> write(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i2.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EncryptedData encrypt(String? plaintext, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [plaintext, pin]),
            returnValue: _FakeEncryptedData_0(
              this,
              Invocation.method(#encrypt, [plaintext, pin]),
            ),
          )
          as _i2.EncryptedData);

  @override
  String decrypt(_i2.EncryptedData? encrypted, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [encrypted, pin]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#decrypt, [encrypted, pin]),
            ),
          )
          as String);

  @override
  bool verifyPin(_i2.EncryptedData? encrypted, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [encrypted, pin]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [Bip39Service].
///
/// See the documentation for Mockito's code generation for more information.
class MockBip39Service extends _i1.Mock implements _i7.Bip39Service {
  MockBip39Service() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateMnemonic() =>
      (super.noSuchMethod(
            Invocation.method(#generateMnemonic, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#generateMnemonic, []),
            ),
          )
          as String);

  @override
  bool validateMnemonic(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#validateMnemonic, [mnemonic]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Uint8List mnemonicToSeed(String? mnemonic, {String? passphrase = ''}) =>
      (super.noSuchMethod(
            Invocation.method(
              #mnemonicToSeed,
              [mnemonic],
              {#passphrase: passphrase},
            ),
            returnValue: _i8.Uint8List(0),
          )
          as _i8.Uint8List);

  @override
  String normalizeMnemonic(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#normalizeMnemonic, [mnemonic]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#normalizeMnemonic, [mnemonic]),
            ),
          )
          as String);
}

/// A class which mocks [KeyDerivationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyDerivationService extends _i1.Mock
    implements _i3.KeyDerivationService {
  MockKeyDerivationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Uint8List derivePrivateKey(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#derivePrivateKey, [mnemonic]),
            returnValue: _i8.Uint8List(0),
          )
          as _i8.Uint8List);

  @override
  _i8.Uint8List derivePublicKey(_i8.Uint8List? privateKey) =>
      (super.noSuchMethod(
            Invocation.method(#derivePublicKey, [privateKey]),
            returnValue: _i8.Uint8List(0),
          )
          as _i8.Uint8List);

  @override
  String deriveAddress(_i8.Uint8List? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#deriveAddress, [publicKey]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#deriveAddress, [publicKey]),
            ),
          )
          as String);

  @override
  _i3.WalletKeys deriveWalletKeys(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#deriveWalletKeys, [mnemonic]),
            returnValue: _FakeWalletKeys_1(
              this,
              Invocation.method(#deriveWalletKeys, [mnemonic]),
            ),
          )
          as _i3.WalletKeys);
}
