// Mocks generated by Mockito 5.4.6 from annotations
// in aimo_wallet/test/features/transaction/domain/usecases/sign_transaction_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i11;

import 'package:aimo_wallet/core/crypto/wallet_engine.dart' as _i2;
import 'package:aimo_wallet/core/vault/secure_vault.dart' as _i5;
import 'package:aimo_wallet/features/transaction/domain/entities/transaction.dart'
    as _i3;
import 'package:aimo_wallet/features/transaction/domain/services/transaction_signer.dart'
    as _i9;
import 'package:aimo_wallet/features/wallet/presentation/controllers/auth_controller.dart'
    as _i10;
import 'package:flutter/services.dart' as _i13;
import 'package:flutter/widgets.dart' as _i14;
import 'package:get/get.dart' as _i4;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWalletCreationResult_0 extends _i1.SmartFake
    implements _i2.WalletCreationResult {
  _FakeWalletCreationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalletImportResult_1 extends _i1.SmartFake
    implements _i2.WalletImportResult {
  _FakeWalletImportResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountDerivationResult_2 extends _i1.SmartFake
    implements _i2.AccountDerivationResult {
  _FakeAccountDerivationResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignedTransaction_3 extends _i1.SmartFake
    implements _i3.SignedTransaction {
  _FakeSignedTransaction_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_4<T> extends _i1.SmartFake
    implements _i4.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SecureVault].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureVault extends _i1.Mock implements _i5.SecureVault {
  MockSecureVault() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> storeMnemonic(
    String? mnemonic,
    String? pin, {
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeMnemonic,
              [mnemonic, pin],
              {#address: address},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> retrieveMnemonic(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#retrieveMnemonic, [pin]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#retrieveMnemonic, [pin]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<bool> hasWallet() =>
      (super.noSuchMethod(
            Invocation.method(#hasWallet, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> deleteWallet() =>
      (super.noSuchMethod(
            Invocation.method(#deleteWallet, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getWalletAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getWalletAddress, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<bool> verifyPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [pin]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> updatePin(String? oldPin, String? newPin) =>
      (super.noSuchMethod(
            Invocation.method(#updatePin, [oldPin, newPin]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [WalletEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletEngine extends _i1.Mock implements _i2.WalletEngine {
  MockWalletEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WalletCreationResult createWallet() =>
      (super.noSuchMethod(
            Invocation.method(#createWallet, []),
            returnValue: _FakeWalletCreationResult_0(
              this,
              Invocation.method(#createWallet, []),
            ),
          )
          as _i2.WalletCreationResult);

  @override
  _i2.WalletImportResult importWallet(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#importWallet, [mnemonic]),
            returnValue: _FakeWalletImportResult_1(
              this,
              Invocation.method(#importWallet, [mnemonic]),
            ),
          )
          as _i2.WalletImportResult);

  @override
  _i2.AccountDerivationResult deriveAccount(String? mnemonic, int? index) =>
      (super.noSuchMethod(
            Invocation.method(#deriveAccount, [mnemonic, index]),
            returnValue: _FakeAccountDerivationResult_2(
              this,
              Invocation.method(#deriveAccount, [mnemonic, index]),
            ),
          )
          as _i2.AccountDerivationResult);

  @override
  _i8.Uint8List derivePrivateKeyForAccount(
    String? mnemonic, {
    int? index = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePrivateKeyForAccount,
              [mnemonic],
              {#index: index},
            ),
            returnValue: _i8.Uint8List(0),
          )
          as _i8.Uint8List);

  @override
  bool validateMnemonic(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#validateMnemonic, [mnemonic]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [TransactionSigner].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionSigner extends _i1.Mock implements _i9.TransactionSigner {
  MockTransactionSigner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.SignedTransaction> signTransaction({
    required _i3.EvmTransaction? transaction,
    required _i8.Uint8List? privateKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signTransaction, [], {
              #transaction: transaction,
              #privateKey: privateKey,
            }),
            returnValue: _i6.Future<_i3.SignedTransaction>.value(
              _FakeSignedTransaction_3(
                this,
                Invocation.method(#signTransaction, [], {
                  #transaction: transaction,
                  #privateKey: privateKey,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.SignedTransaction>);

  @override
  _i6.Future<_i3.SignedTransaction> signTransactionSecure({
    required _i3.EvmTransaction? transaction,
    required _i8.Uint8List? privateKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signTransactionSecure, [], {
              #transaction: transaction,
              #privateKey: privateKey,
            }),
            returnValue: _i6.Future<_i3.SignedTransaction>.value(
              _FakeSignedTransaction_3(
                this,
                Invocation.method(#signTransactionSecure, [], {
                  #transaction: transaction,
                  #privateKey: privateKey,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.SignedTransaction>);

  @override
  int estimateTransactionSize(_i3.EvmTransaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#estimateTransactionSize, [transaction]),
            returnValue: 0,
          )
          as int);

  @override
  BigInt calculateTransactionFee(_i3.EvmTransaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTransactionFee, [transaction]),
            returnValue: _i7.dummyValue<BigInt>(
              this,
              Invocation.method(#calculateTransactionFee, [transaction]),
            ),
          )
          as BigInt);

  @override
  BigInt calculateTotalCost(_i3.EvmTransaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTotalCost, [transaction]),
            returnValue: _i7.dummyValue<BigInt>(
              this,
              Invocation.method(#calculateTotalCost, [transaction]),
            ),
          )
          as BigInt);
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i10.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLocked =>
      (super.noSuchMethod(Invocation.getter(#isLocked), returnValue: false)
          as bool);

  @override
  bool get isUnlocked =>
      (super.noSuchMethod(Invocation.getter(#isUnlocked), returnValue: false)
          as bool);

  @override
  bool get biometricEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#biometricEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get biometricAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#biometricAvailable),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get failedAttempts =>
      (super.noSuchMethod(Invocation.getter(#failedAttempts), returnValue: 0)
          as int);

  @override
  bool get isLockedOut =>
      (super.noSuchMethod(Invocation.getter(#isLockedOut), returnValue: false)
          as bool);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i11.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> unlockWallet(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#unlockWallet, [pin]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void lockWallet() => super.noSuchMethod(
    Invocation.method(#lockWallet, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetAutoLockTimer() => super.noSuchMethod(
    Invocation.method(#resetAutoLockTimer, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> setAutoLockDuration(Duration? duration) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoLockDuration, [duration]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> verifyPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [pin]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> changePin(String? oldPin, String? newPin) =>
      (super.noSuchMethod(
            Invocation.method(#changePin, [oldPin, newPin]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> toggleBiometric(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBiometric, [enabled]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> authenticateWithBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithBiometric, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetFailedAttempts() => super.noSuchMethod(
    Invocation.method(#resetFailedAttempts, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListener(_i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i11.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListenerId(Object? key, _i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  bool handleStartBackGesture(_i13.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i13.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> didPushRouteInformation(
    _i14.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i11.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i11.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i11.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i6.Future<_i11.AppExitResponse>.value(
              _i11.AppExitResponse.exit,
            ),
          )
          as _i6.Future<_i11.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}
